version: "3.7"
services:
  openttd:
    image: pvillaverde/openttd-jgr:1.0.63
    restart: always
    ports:
      - "0.0.0.0:3979:3979"
      - "0.0.0.0:3977:3977"
    environment:
      loadgame: "true"
      #loadgame: "last-autosave"
      savename: "galizattd.scn"
      PUID: "1000"
      PGID: "1000"
      debug: "2"
    volumes:
      - ./data:/home/openttd/.openttd/
